---
apiVersion: v1
kind: Pod
metadata:
  name: all
spec:
  containers:
    - name: benchmark
      command: ["k8s/k8s-echo-client.sh"]
      # These are options passed to the benchmark-runner script
      args:
        - "--output-file"
        - "aeron-echo_java-k8s"
        - "--message-rate"
        - "101K"
        - "--message-length"
        - "288"
        - "--iterations"
        - "60"
