# This file contains the overrides for aeron-echo-dpdk test

resources:
  - ../base
patches:
  # Media driver specific config
  - path: aeronmd-java.yml
    target:
      kind: Pod
  # Settings for the benchmark
  - path: echo-client.yml
    target:
      kind: Pod
      name: aeron-benchmark-1
  # Local environment specific settings
  - target:
      kind: Pod
    path: settings.yml
